spring:
  application:
    name: "clone-one-port"
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

pg:
  tosspayments:
    base-url: ${TOSS_PAYMENTS_BASE_URL:https://api.tosspayments.com/v1/}
    secret-key: ${TOSS_PAYMENTS_SECRET_KEY:test_sk_0RnYX2w532257LzwRYBK3NeyqApQ}
    connect-timeout-seconds: ${TOSS_PAYMENTS_CONNECT_TIMEOUT_SECONDS:20}
    write-timeout-seconds: ${TOSS_PAYMENTS_WRITE_TIMEOUT_SECONDS:60}
    read-timeout-seconds: ${TOSS_PAYMENTS_READ_TIMEOUT_SECONDS:60}
    retry-on-connection-failure: ${TOSS_PAYMENTS_RETRY_ON_CONNECTION_FAILURE:true}

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:13306/wanted_preonboarding?serverTimezone=UTC&characterEncoding=UTF-8
    username: wanted
    password: backend
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:oneport-test;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력
